### ISSUE TITLE
which php version? how many version we would support?

### ISSUE THREAD

**Issue by sensorario** [studiomado/query-bundle#102]
Until now we have been worked without care about php version. Starting from v2.2.10 php version is forced to 7.0 because some software works with that version. According to this fact we can still mantains version 2.2 but also develop new version against most recent php71 version.

| version          | supported versions |
| ------------- |:-------------------:|
| 2.2                 | 7.0.8                         |
| master           | >= 7.1           |

Two version could be always maintained: 2.2 and master. Each bug found in version 2.2 will be merged to master.

/cc @AlessandroMinoccheri @davidedonattini @mmedelin @simocheccoli @orociscaverai

**Comment by AlessandroMinoccheri** [comment]
I think that master branch and future features should be developed with last php versions so this means that version 2.2 shouldn't be upgraded with new php version.

We will mantain two versions in this way but we could do that 👍

**Comment by sensorario** [comment]
👍
