### ISSUE TITLE
Limit = -1 for no limit results

### ISSUE THREAD

**Issue by gherry77** [studiomado/query-bundle#114]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | yes
| QueryBundle version  | 2.3.3

--- 

Is it possible like **DataTables** put in the request `limit = -1`

 for no limit results?

### **Example:**
`&limit=-1`

So we can avoid: `&limit=999999`

**Comment by AlessandroMinoccheri** [comment]
We can handle It!

Thanks

**Comment by AlessandroMinoccheri** [comment]
Instead of use ```paginateResults``` you can use doctrine function in your controller for example:

```
->setRequest($request)
->getQuery()
->getResult()
```

**Comment by gherry77** [comment]
@AlessandroMinoccheri Sometimes I need the same endpoint returns paginated results and sometimes without pagination
Do you suggest to intercept that in the controller
## Example

```
    public function getCustomersAction(Request $request)
    {
        $repo = $this->get(\AppBundle\Services\QueryBuilder::class)
            ->getRepository(\GammaBundle\Entity\Customer::class);

        if ($this->RequestHasNoLimit($request) {
               return $repo->setRequest($request)
                         ->getQuery()
                         ->getResult();
        }
        return $repo->findAllPaginated();
    }
```

**Comment by AlessandroMinoccheri** [comment]
There are some solutions:
* into your controller if you get a limit < 1 you can call doctrine method ```getResult```
* we can add a condition inside ```paginateResult``` method where if limit < 1 we send to PagerFanta a big limit like 9999999 
* we can  add a condition inside ```paginateResult``` method where if limit < 1 we call another method that replicate ```getResult``` of doctrine

The point is that: if you don't need pagination you shouldn't call ```paginateResult``` I think, but we can handle It in many ways as you seen

**Comment by LuXDAmore** [comment]
Le paginazioni Front-End di molti componenti utilizzano '-1', quindi sarebbe utile anche per poterlo utilizzare senza dover gestire questa casistica.

**Comment by sensorario** [comment]
@gherry77 you are using version 2.2. Please fix release in your feature request's description.
