### ISSUE TITLE
Mandatory parameters missing when generate url

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [studiomado/query-bundle#12]
When inside an url like this:  

```
entities/{id}/someAction
```

returns this error when is use inside the repository paginateResults() method:

```
Some mandatory parameters are missing (\"id\") to generate a URL for route \"app_entity_getentity\".",
```

The solution now is to overwrite the function customQueryStringValues inside the repository like this:

```
public function customQueryStringValues()
    {
        return['id'];
    }
```

But It could be better to autodetection url parameters

**Comment by sensorario** [comment]
Is not a bug, is a feature ^_^. Method `customQueryStringValues` were just added to customize query string variables that needs to be sent in pagination. We can improve code removing the needs of override.

**Comment by sensorario** [comment]
It could be an API improvement. I suggest this for next minor release.
