### ISSUE TITLE
Deny access to not-exposed fields

### ISSUE THREAD

**Issue by mmedelin** [studiomado/query-bundle#48]
It would be nice to have an option to deny access to not-exposed fields while filtering.

**Comment by sensorario** [comment]
This is not so clear feature. User permissions and roles are not responsibility of a query builder. But we can create and adapter of the query builder able to talk with symfony users, so then we can manage here queries dependent of user roles.

**Comment by AlessandroMinoccheri** [comment]
We can add a configuration to deny access to not exposed field from JMS/Serializer I think, an adapter could be a solution also

**Comment by sensorario** [comment]
An adapter?

**Comment by AlessandroMinoccheri** [comment]
An adapter to filter request and deny accesso to not exposed field, It can remove wrong filtering for example

**Comment by sensorario** [comment]
Could you open a PR to explain?

**Comment by AlessandroMinoccheri** [comment]
Another solution it could be to write own annotation on entities and we read that to understand which field can be filtered.

**Comment by sensorario** [comment]
The PR #62 solve this issue.
