### ISSUE TITLE
Get result without pagination

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [studiomado/query-bundle#57]
Is possible to have a single result without pagination?

Example: I need to get a specific record by Id with custom filter not passed by url.

I would like to do something like this:

```
            $filters['id|eq'] = $id;
            $filters['myCustomFilter|eq] = 'foo';

            $result = $this->getDoctrine()
                ->getRepository('AppBundle:Entity')
                ->setRequestWithFilter($request, $filters)
                ->getResult(); //or find
```

**Comment by sensorario** [comment]
Absolutely yes! I’ll write a wiki page or sonething like that asap!!
