### ISSUE TITLE
getEntityAlias function doesn't exists

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [studiomado/query-bundle#85]
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     | no
| QueryBundle version  | 2.2.x

--- 

If you use ```buildSelectValue``` from ```QueryBuilderFactory``` and you are not set ```select```It calls ```$this->getEntityAlias```function that doesn't extsts

**Comment by sensorario** [comment]
Good catch!!!. buildSelectValue is never used. And this is the reason this error was never reached in our application. We can ...

 - fix this error adding a getEntityAlias() function or, ...
 - just remove buildSelectValue()

**Comment by AlessandroMinoccheri** [comment]
I think that the best solution could be remove buildSelectValue
